# A declaration of an instance that this hApp needs to have installed.
# `name` here is just an internal name to reference the given DNA inside the rest of this bundle.

bridges = []

[[instances]]
name = "Passthrough"
id = "instance"
dna_hash = "QmcjoGNWszyb9pbZEXkj9Ujk8vpycRL47VqTSjfvrU4JVs"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.8/passthrough-dna.dna.json"


[[UIs]]
name = "Passthrough Test hApp"
id = "passthrough"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.8/ui.zip"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "instance"


