
bridges = []

# A declaration of an instance that this hApp needs to have installed.
# `name` here is just an internal name to reference the given DNA inside the rest of this bundle.
[[instances]]
name = "Holo pacman"
id = "invaders"
dna_hash = "QmQHdELR3ccvdBffpSQ1g5RwkEpyHKHi6L5u9FC3QdzXwr"
# Optional, might also be retrieved from hchc via hash long-term
uri = "https://github.com/eyss/holo-invaders-back/releases/download/1/holo-invaders-back.dna.json"
[[UIs]]
name = "Holo invaders"
# Optional, might also be retrieved from hchc via hash long-term
uri = "https://github.com/eyss/h-pacman/releases/download/1/ui.zip"

[[UIs.instance_references]]
ui_handle = "invaders"
instance_id = "invaders"
