bridges = []

[[instances]]
name = "Communities"
id = "__communities"
dna_hash = "QmfAi6wBzvRzMwU343L1YWR9f1uPGmFuzHUJYdJyNKtQFs"
uri = "https://github.com/Holo-Host/holo-communities/releases/download/0.0.6/holo-communities-dna.dna.json"

[[UIs]]
name = "Communities"
uri = "https://github.com/Holo-Host/holo-communities/releases/download/0.0.6/holo-communities.zip"

[[UIs.instance_references]]
ui_handle = "__communities"
instance_id = "__communities"
